TPM Hardware interfaces requirements added
lpn-plant/lpntpm-docs pull request #6
Opened 2021-11-22 09:33 UTC by acwiek

2021-11-25 07:38 UTC, macpijan requested changes
Please use grammarly.com https://languagetool.org/ or similar tools prior to publishing docs

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +The first interface, that we looking to implement is SPI. That's mostly because we
```suggestion
The first interface, that we are looking to implement is SPI. That's mostly because we
```

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +think it is the easiest way is to start.
```suggestion
think it is the easiest way to start.
```

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +We are planning to use lpntpm with an embedded platform as Raspberry Pi.
```suggestion
We are planning to use lpnTPM with an embedded platform (such as Raspberry Pi) for test purposes.
```

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +As one of our requirements is to communicate with motherboards using SPI we
```suggestion
As one of our requirements is to communicate with motherboards using SPI, we
```

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +[TCG PC Client Platform TPM Profile Specification for TPM 2.0](https://trustedcomputinggroup.org/wp-content/uploads/PC-Client-Specific-Platform-TPM-Profile-for-TPM-2p0-v1p04_r0p37_pub-1.pdf)
This is too raw. Please make a sentence(s) out of it. E.g. as explaiend in []() pages XXX, there are following requirements for ....

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +STM32L4 limits SPI speed up to `APB2/2` thus our maximum speed of SPI interface
```suggestion
STM32L4 limits SPI speed up to `APB2/2`, thus our maximum speed of the SPI interface
```

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +is theoretically is 40MHz so we are good to go.
```suggestion
theoretically is 40MHz so we are good to go.
```

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +[RM0351 Reference manual](https://www.st.com/resource/en/reference_manual/rm0351-stm32l47xxx-stm32l48xxx-stm32l49xxx-and-stm32l4axxx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf)
As above. Please provide some more context to this link.

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +LPC (Low Pin Count) Interface it is not available in popular microcontrollers.
```suggestion
LPC (Low Pin Count) Interface is not available in popular microcontrollers.
```

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +First of all we would like to use some other hardware interfaces, to be able to
```suggestion
First of all, we would like to use some other hardware interfaces, to be able to
```

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +archive communication.
archive? Maybe `achieve`? I am not sure what was the desired meaning here.

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +
extra empty line

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +
extra empty lines

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +[Lattice Design software - LPC Controller](https://www.latticesemi.com/products/designsoftwareandip/intellectualproperty/referencedesigns/referencedesigns02/lpcbuscontroller)
Leaving references like this decreases the readability of the whole text. We can either put all of them in some `References` section at the bottom of the file. Or we can incorporate them as links in the text some how. Here you could use: [offers LPC implementation for FPGA's](https://www.latticesemi.com/products/designsoftwareandip/intellectualproperty/referencedesigns/referencedesigns02/lpcbuscontroller) in below sentence

2021-11-25 07:38 UTC, macpijan commented on docs/hardware_interfaces.md
> +In our opinion bit-banging of such a fast interface (33MHz) will not be reasonable
But maybe we will change it finally. Please include the software implementation you have found, which could be potentially adapted. Please also define what kind of minimum clock we would need. Which STM32 we have considered switching to if we would need higher clock rates?

2021-11-30 07:20 UTC, acwiek commented
I think we are good to go. Sorry for the Grammarly issues - it won't happen again as I've changed my development/writing flow

2021-12-10 09:27 UTC, macpijan approved these changes

2021-12-10 09:27 UTC, merged